/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-04-22 02:48:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.day0420;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ShopDetailPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.0.js\"></script>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Gamja+Flower&family=Jua&family=Lobster&family=Nanum+Brush+Script&display=swap\" rel=\"stylesheet\">  \n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("	div.detail{\n");
      out.write("		margin-top: 100px;\n");
      out.write("		margin-left: 200px;\n");
      out.write("		font-size: 25px;\n");
      out.write("		font-family: 'Jua';\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	$(function() {\n");
      out.write("		init(); //처음 시작시 dto데이터 넣어주기\n");
      out.write("		\n");
      out.write("		//메인페이지로 가는 이벤트\n");
      out.write("		$(\"#btnmain\").click(function() {\n");
      out.write("			history.back(); //이전 페이지로 이동\n");
      out.write("			//location.href=\"ShopJson.jsp\"\n");
      out.write("			\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		$(\"#btndelete\").click(function(){\n");
      out.write("			var ans = confirm(\"삭제하려면 [확인]버튼을 눌러주세요\");\n");
      out.write("			if(ans){\n");
      out.write("				$.ajax({\n");
      out.write("					type: \"get\",\n");
      out.write("					dataType: \"html\",\n");
      out.write("					url: \"delete.jsp\",\n");
      out.write("					data: {\"num\":$(\"#num\").val()},\n");
      out.write("					success:function(){\n");
      out.write("						alert(\"삭제되었습니다\");\n");
      out.write("						//Shopjson.html로 이동 \n");
      out.write("						location.href=\"Shopjson.html\";\n");
      out.write("					}\n");
      out.write("				});\n");
      out.write("			}\n");
      out.write("		}); \n");
      out.write("		\n");
      out.write("		//수정 버튼\n");
      out.write("		$(\"#btnupdate\").click(function(){\n");
      out.write("			$.ajax({\n");
      out.write("				type: \"get\",\n");
      out.write("				dataType: \"json\",\n");
      out.write("				url: \"DetailJson.jsp\",\n");
      out.write("				data: {\"num\":$(\"#num\").val()},\n");
      out.write("				success:function(data){\n");
      out.write("					$(\"#usangpum\").val(data.sangpum);\n");
      out.write("					$(\"#uprice\").val(data.price);\n");
      out.write("					$(\"#ucnt\").val(data.cnt);\n");
      out.write("					$(\"#uphoto\").val(data.photo);\n");
      out.write("					$(\"#umyphoto\").attr(\"src\",data.photo);\n");
      out.write("					$(\"#ipgoday\").val(data.ipgoday);\n");
      out.write("					$(\"#ucolor\").val(data.color);\n");
      out.write("					//console.log(data);\n");
      out.write("				}\n");
      out.write("			});\n");
      out.write("	\n");
      out.write("			 $(\"#myModal\").modal();\n");
      out.write("		});\n");
      out.write("			 \n");
      out.write("		$(\"#ubtnupdate\").click(function(){\n");
      out.write("			 //전체 폼데이터 읽기\n");
      out.write("			var fdata = $(\"#ufrm\").serialize(); //serialize는 num값으로 불러옴 \n");
      out.write("			//alert(fdata);\n");
      out.write("			$.ajax({\n");
      out.write("				type: \"post\",\n");
      out.write("				dataType: \"html\",\n");
      out.write("				url: \"update.jsp\",\n");
      out.write("				data: fdata,\n");
      out.write("				success: function(){\n");
      out.write("					location.reload(); //새로고침\n");
      out.write("				}\n");
      out.write("			});\n");
      out.write("		});	\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	function init() {\n");
      out.write("		$.ajax({\n");
      out.write("			type: \"get\",\n");
      out.write("			dataType: \"json\",\n");
      out.write("			url: \"DetailJson.jsp\",\n");
      out.write("			data: {\"num\":$(\"#num\").val()},\n");
      out.write("			success:function(data){\n");
      out.write("				console.log(data);\n");
      out.write("				$(\"#photo\").attr(\"src\",data.photo);\n");
      out.write("			 	$(\"#photo\").css(\"border\",\"4px solid gray\");\n");
      out.write("			 	$(\"#sangpum\").text(data.sangpum);\n");
      out.write("			 	$(\"#price\").text(data.price + \"원\");\n");
      out.write("			 	$(\"#color\").text(data.color);\n");
      out.write("			 	$(\"#color\").css({\n");
      out.write("			 		\"background-color\":data.color,\n");
      out.write("			 		\"float\":\"right\"\n");
      out.write("			 	});\n");
      out.write("			 	$(\"#cnt\").text(data.cnt + \"개\");\n");
      out.write("			 	$(\"#ipgoday\").text(data.ipgoday);		\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("</head>\n");

	String num = request.getParameter("num");

      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<input type=\"hidden\" id=\"num\" value=\"");
      out.print(num);
      out.write("\">\n");
      out.write("<div class=\"detail\">\n");
      out.write("	<table class=\"table table-bordered\" style=\"width: 600px;\" >\n");
      out.write("	<caption><h1>상품 상세 페이지</h1></caption>\n");
      out.write("		<tr>\n");
      out.write("			<td width=\"300\">\n");
      out.write("				<img src=\"\" width=\"300\" height=\"400\" id=\"photo\">\n");
      out.write("			</td>\n");
      out.write("			<td>\n");
      out.write("				<h2>상품명 : <span id=\"sangpum\"></span></h2>\n");
      out.write("				<h2>색 상 : <div id=\"color\"></div></h2>\n");
      out.write("				<h2>가 격 : <span id=\"price\"></span></h2>\n");
      out.write("				<h2>수 량 : <span id=\"cnt\"></span></h2>\n");
      out.write("				<h2>입고일 : <span id=\"ipgoday\"></span></h2>\n");
      out.write("			</td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<td colspan=\"2\" align=\"center\">\n");
      out.write("				<button type=\"button\" class=\"btn btn-success\"\n");
      out.write("				style=\"width: 120px;\" id=\"btnmain\">메인</button>\n");
      out.write("				\n");
      out.write("				<button type=\"button\" class=\"btn btn-info\"\n");
      out.write("				style=\"width: 120px;\" id=\"btnupdate\" num=");
      out.print(num);
      out.write(">수정</button>\n");
      out.write("				\n");
      out.write("				<button type=\"button\" class=\"btn btn-danger\"\n");
      out.write("				style=\"width: 120px;\" id=\"btndelete\" num=");
      out.print(num);
      out.write(">삭제</button>\n");
      out.write("			</td>\n");
      out.write("		</tr>\n");
      out.write("	</table>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!--수정 다이얼로그 Modal -->\n");
      out.write("  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("    \n");
      out.write("      <!-- Modal content-->\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("          <h4 class=\"modal-title\">상품 수정</h4>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("         \n");
      out.write("          <!-- 수정폼 -->\n");
      out.write("          <form action=\"#\" id=\"ufrm\" class=\"form-inline\">\n");
      out.write("          <input type=\"hidden\" id=\"unum\" value=\"");
      out.print(num);
      out.write("\" name=\"unum\">\n");
      out.write("		<table class=\"table table-bodered\" style=\"width: 400px;\">\n");
      out.write("			<tr>\n");
      out.write("				<th bgcolor=\"pink\" style=\"width: 100px;\">상품명</th>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"text\" id=\"usangpum\" name=\"usangpum\"\n");
      out.write("						class=\"form-control\">\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th bgcolor=\"pink\" style=\"width: 100px;\">상품사진</th>\n");
      out.write("				<td>\n");
      out.write("					<select id=\"uphoto\" name=\"uphoto\" class=\"form-control\" style=\"width: 120px;\">\n");
      out.write("					<script type=\"text/javascript\">\n");
      out.write("						var data = [\"라운드티\",\"블랙원피스\",\"화이트원피스\",\n");
      out.write("								\"도트원피스\",\"블랙조끼\",\"꽃무늬원피스\",\"프릴원피스\",\n");
      out.write("								\"반팔원피스\",\"레이스원피스\",\"블랙코트\",\"체크쿠션\"];\n");
      out.write("						var s = \"\";\n");
      out.write("						for(i=0; i<=10; i++) {\n");
      out.write("							s += \"<option value='../image2/\" + (i+1) + \".jpg'>\" + data[i] + \"</option>\";\n");
      out.write("						}\n");
      out.write("						document.write(s);\n");
      out.write("					</script>\n");
      out.write("					</select>\n");
      out.write("					<img src=\"\" id=\"umyphoto\" width=\"60\" height=\"60\">\n");
      out.write("					<script>\n");
      out.write("						//변경시 이벤트\n");
      out.write("						$(\"#uphoto\").change(function(){\n");
      out.write("							$(\"#umyphoto\").attr(\"src\",$(this).val());\n");
      out.write("						});\n");
      out.write("					</script>\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th bgcolor=\"pink\" style=\"width: 100px;\">색상</th>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"color\" id=\"ucolor\" name=\"ucolor\"\n");
      out.write("						class=\"form-control\" value=\"#fffccc\"\n");
      out.write("						style=\"width: 80px;\">\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th bgcolor=\"pink\" style=\"width: 100px;\">단가</th>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"text\" id=\"uprice\" name=\"uprice\"\n");
      out.write("						class=\"form-control\">\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th bgcolor=\"pink\" style=\"width: 100px;\">수량</th>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"number\" id=\"ucnt\" name=\"ucnt\"\n");
      out.write("						class=\"form-control\" min=\"1\" max=\"5\" value=\"1\">\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th bgcolor=\"pink\" style=\"width: 100px;\">입고일</th>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"date\" id=\"uipgoday\" name=\"uipgoday\"\n");
      out.write("						class=\"form-control\" value=\"2022-04-20\">\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td colspan=\"2\" align=\"center\">\n");
      out.write("					<button type=\"button\" class=\"btn btn-info\"\n");
      out.write("					style=\"width: 130px;\" id=\"ubtnupdate\"\n");
      out.write("					data-dissmiss=\"modal\">DB수정</button>\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("	</form>\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
